### ISSUE TITLE
Pedido para fazer Atividade05

### ISSUE THREAD

**Issue by nefestor** [andreendo/Exemplo01#16]
Faltei na quarta-feira e não consegui realizar a atividade05, peço que seja criado o 'plus' do atividade para que seja entregue até a semana que vem.

**Comment by andreendo** [comment]
No momento do cálculo da média final, não é realizado a arredondamento quando temos 2 ou mais casas decimais. Por exemplo, na versão atual se o cálculo da nota final der 5,96 a nota considerada é 5,9. No entanto, neste caso a nota deveria ser arredondada para 6,0. Implemente essa alteração e submeta o pull request seguindo o ciclo TDD. Garanta a originalidade da sua resposta.

**Comment by andreendo** [comment]
A atividade acima pedida não foi realizada, sem nota na atividade 05.

**Comment by nefestor** [comment]
"No momento do cálculo da média final, não é realizado a arredondamento quando temos 2 ou mais casas decimais."

**Teste do arredondamento falhando.** 

```
@Test
    public void testNotaFinalArredondaMedia6() {
        Aluno aluno = new Aluno("RA", "Tiago Coelho");

        //Media 4.6
        aluno.addNotaAtividadePratica(5.0);
        aluno.addNotaAtividadePratica(10.0);
        aluno.addNotaAtividadePratica(7.0);
        aluno.addNotaAtividadePratica(0.0);
        aluno.addNotaAtividadePratica(1.0);
        double mediaRAA = (5.0 + 10.0 + 7.0 + 0.0 + 1.0)/5.0;

        aluno.setNotaProjeto(5.0);
        aluno.setNotaRAA(8.28);
        assertEquals(6.0, aluno.getNF(), 0.01);
    }
```

**Teste corrigido e funcionando.**

```
 double getNF() {
        
        double notaFinal = 0;
        if(notaRAA < 0) {
            notaFinal = ((notaProjeto + getNAP()) / 2.0);
            BigDecimal bd = new BigDecimal(notaFinal).setScale(1, RoundingMode.HALF_EVEN);
            return bd.doubleValue();
        }
        
        notaFinal =  (notaProjeto + getNAP() + notaRAA) / 3.0;
        BigDecimal bd = new BigDecimal(notaFinal).setScale(1, RoundingMode.HALF_EVEN);
	if(bd.doubleValue() >= 6.0) {
            return 6.0;
        }
        return bd.doubleValue();
  }
```

Ambos os códigos foram commitados ontem, no repositório [TATS-Respostas/Atividade05](https://github.com/nefestor/TATS-Respostas/tree/master/Atividade05)
