### ISSUE TITLE
Pedido Atividade 5

### ISSUE THREAD

**Issue by GabrieldeCarli** [andreendo/Exemplo01#20]
Pedido Atividade 5 , pois faltei no dia da mesma.

**Comment by andreendo** [comment]
No momento do cálculo da média final, não é realizado a arredondamento quando temos 2 ou mais casas decimais. Por exemplo, na versão atual se o cálculo da nota final der 5,96 a nota considerada é 5,9. No entanto, neste caso a nota deveria ser arredondada para 6,0. Implemente essa alteração e submeta o pull request seguindo o ciclo TDD. Garanta a originalidade da sua resposta.
