### ISSUE TITLE
Pedido atividade 05

### ISSUE THREAD

**Issue by AndersonMSoares** [andreendo/Exemplo01#22]
Gostaria de ter a oportunidade de fazer a atividade 05.

**Comment by andreendo** [comment]
No momento do cálculo da média final, não é realizado a arredondamento quando temos 2 ou mais casas decimais. Por exemplo, na versão atual se o cálculo da nota final der 5,96 a nota considerada é 5,9. No entanto, neste caso a nota deveria ser arredondada para 6,0. Implemente essa alteração e submeta o pull request seguindo o ciclo TDD. Garanta a originalidade da sua resposta.
