### ISSUE TITLE
Pedido Atividade 06 e Link Atividade 05

### ISSUE THREAD

**Issue by nefestor** [andreendo/Exemplo01#26]
Professor, bom dia. Não consegui terminar a tempo a atividade 6, estava tentando utilizar uma biblioteca externa para fazer o cálculo do desvio padrão e não deu certo, além do meu Sonar não está funcionando conforme esperado (mandei print no Moodle, na Atividade 6). 

Em relação a Atividade 05, eu não criei um repositório novo, fiz uma cópia do 'Exemplo01' e coloquei na pasta 'Atividade 05' do repositório [TATS-Respostas](https://github.com/nefestor/TATS-Respostas/tree/master/Atividade05), estou enviando isso porque fiquei com 0 na atividade 5.

**Comment by andreendo** [comment]
Não precisava usar uma biblioteca externa, a ideia era que você implementasse já que é um cálculo simples e o TDD deveria ser aplicado. A atividade 06 encerrou ontem. Sobre o Sonar, os arquivo do travis deveria estar na raiz do projeto. 

Respondi sobre a atividade 05 na outra thread.

**Comment by nefestor** [comment]
Professor, no Fork [Exemplo01](https://github.com/nefestor/Exemplo01), há a implementação do TDD da parte 1, feita em sala.

A parte 2 eu fiz ela toda também, mas os commits não foram feitos porque eu não sabia o que era pra commitar exatamente, tanto que eu adicionei meu projeto ao [Trevis ](https://travis-ci.org/nefestor/TATS-Respostas), só confundi o repositório, era o Exemplo01 e eu adicionei o TATS-Respostas e o meu Sonar, eu adicionava o Token e ele não buildava o projeto, dava algum erro no Bootstrap Index, não corrigi porque achei que eu pudesse entregar depois.

Já a Parte 3 da atividade, do desvio Padrão eu não terminei e achei que teria a possibilidade de estender o prazo, visto que ninguem terminou essa atividade em sala, por completo (problemas com proxy/sonar) e o sr. definiu a data inicial de entrega para ontem... Acabou ficando confuso essa relação de data e o 'plus', quanto a essa atividade.

Por isso não entendi o 0 na atividade e a não possibilidade de realizar ela com o prazo estendido.
